version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: careertrack-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      # Mount storage for persistence
      - ./storage:/var/www/html/storage
      # Mount database for development
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: careertrack-dev
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: php artisan serve --host=0.0.0.0 --port=8000
    profiles:
      - dev

networks:
  default:
    name: careertrack-network 