apiVersion: batch/v1
kind: Job
metadata:
  name: careertrack-migration
  namespace: careertrack
spec:
  template:
    spec:
      containers:
      - name: migration
        image: careertrack:latest
        command: ["php", "artisan", "migrate", "--force"]
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: APP_ENV
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: careertrack-secrets
              key: APP_KEY
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: careertrack-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: careertrack-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never
      imagePullSecrets:
      - name: careertrack-registry-secret  # If using private registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: careertrack-seeder
  namespace: careertrack
spec:
  template:
    spec:
      containers:
      - name: seeder
        image: careertrack:latest
        command: ["php", "artisan", "db:seed", "--force"]
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: APP_ENV
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: careertrack-secrets
              key: APP_KEY
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: careertrack-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: careertrack-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: careertrack-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never
      imagePullSecrets:
      - name: careertrack-registry-secret  # If using private registry
