apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: careertrack-storage-pvc
  namespace: careertrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "standard"  # Use "standard" for GKE, adjust for your cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: careertrack-mysql-pvc
  namespace: careertrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: "standard"  # Use "standard" for GKE, adjust for your cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: careertrack-redis-pvc
  namespace: careertrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "standard"  # Use "standard" for GKE, adjust for your cluster
