blank_issues_enabled: false
contact_links:
  - name: 🙋 Need Help?
    url: https://github.com/denisdotdev/careertrack/discussions
    about: Ask questions, share ideas, and get help from the community.